theme: minima
title: SaPi's GitHub Pages Site with Jekyll
author: Samyak Piya
email: samyakpiya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a GitHub Pages Site with Jekyll that I created while learning how GitHub pages work.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
